<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>consoleprobe</AssemblyName>
    <RootNamespace>consoleprobe</RootNamespace>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <RunAnalyzers>false</RunAnalyzers>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
